# Generated by Django 5.0.6 on 2026-01-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vanoperator_operator_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_license_doc',
            field=models.FileField(upload_to='operator_docs/'),
        ),
    ]
