# Generated by Django 5.0.6 on 2026-01-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_location',
        ),
        migrations.AddField(
            model_name='request',
            name='user_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
