# Generated by Django 5.0.6 on 2026-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_request_id_payment_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvan',
            name='operator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
