# Generated by Django 4.2 on 2026-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingvan',
            name='operator_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
