# Generated by Django 4.2 on 2026-01-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_chargingvan_operator_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingvan',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='chargingvan',
            name='operator_name',
        ),
        migrations.AddField(
            model_name='chargingvan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vanoperator'),
        ),
    ]
