# Generated by Django 4.2 on 2026-01-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_chargingvan_operator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanoperator',
            name='is_verified',
            field=models.IntegerField(choices=[(0, 'Not verified'), (1, 'Verified')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='chargingvan',
            name='van_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'UPI')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Compeletd')], default=0),
        ),
        migrations.AlterField(
            model_name='uservehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0),
        ),
    ]
