# Generated by Django 4.2 on 2026-01-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_vanoperator_is_verified_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanoperator',
            name='is_verified',
            field=models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Verified')], default=0),
        ),
    ]
