# Generated by Django 4.2 on 2026-01-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_vanoperator_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='operator_id',
        ),
        migrations.AddField(
            model_name='request',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vanoperator'),
        ),
    ]
