# Generated by Django 5.0.6 on 2026-01-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_request_operator_remove_request_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservehicle',
            name='user_id',
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.user'),
            preserve_default=False,
        ),
    ]
