# Generated by Django 5.0.6 on 2026-01-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_uservehicle_user_id_uservehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operator_feedbacks', to='api.vanoperator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='api.user'),
            preserve_default=False,
        ),
    ]
