# Generated by Django 5.0.6 on 2026-01-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_feedback_operator_id_remove_feedback_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='request',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_requests', to='api.vanoperator'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='vehicle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='api.uservehicle'),
            preserve_default=False,
        ),
    ]
