# Generated by Django 5.0.6 on 2026-01-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_booking_operator_id_booking_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='operator_bookings', to='api.vanoperator'),
            preserve_default=False,
        ),
    ]
