# Generated by Django 5.0.6 on 2026-01-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_booking_request_id_booking_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request',
        ),
        migrations.AddField(
            model_name='booking',
            name='request_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_booking', to='api.vanoperator'),
        ),
    ]
