# Generated by Django 5.0.6 on 2026-01-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_booking_request_booking_request_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.request'),
            preserve_default=False,
        ),
    ]
