# Generated by Django 5.0.6 on 2026-01-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_booking_request_id_booking_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operator_payments', to='api.vanoperator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to='api.user'),
            preserve_default=False,
        ),
    ]
