# Generated by Django 4.2.27 on 2026-01-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('booking_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='ChargingVan',
            fields=[
                ('van_id', models.AutoField(primary_key=True, serialize=False)),
                ('van_number', models.CharField(max_length=15)),
                ('operator_id', models.CharField(max_length=30)),
                ('battery_capacity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chargingvan',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('p_method', models.IntegerField(default=0)),
                ('p_status', models.IntegerField(default=0)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('operator_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('user_location', models.CharField(max_length=255)),
                ('request_status', models.IntegerField(default=0)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('user_phone', models.BigIntegerField()),
                ('user_address', models.CharField(max_length=100)),
                ('role', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('vehicle_company', models.CharField(max_length=30)),
                ('vehicle_name', models.CharField(max_length=30)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uservehicle',
            },
        ),
        migrations.CreateModel(
            name='VanOperator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=30)),
                ('operator_email', models.EmailField(max_length=30, unique=True)),
                ('operator_password', models.CharField(max_length=15)),
                ('operator_phone', models.BigIntegerField()),
                ('operator_license_doc', models.CharField(max_length=150)),
                ('operator_status', models.IntegerField(default=0)),
                ('role', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vanoperator',
            },
        ),
    ]
