# Generated by Django 5.0.6 on 2026-01-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_password',
            field=models.CharField(max_length=255),
        ),
    ]
