# Generated by Django 5.0.6 on 2026-01-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_request_user_location_request_user_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='request_id',
            new_name='booking_id',
        ),
    ]
