# Generated by Django 5.0.6 on 2026-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chargingvan_operator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_password',
            field=models.CharField(max_length=30),
        ),
    ]
