# Generated by Django 4.2 on 2026-01-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_password',
            field=models.CharField(max_length=255),
        ),
    ]
