# Generated by Django 4.2 on 2026-01-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_request_operator_id_request_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_id',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
