# Generated by Django 4.2 on 2026-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_request_user_id_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='operator_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
