# Generated by Django 5.0.6 on 2026-01-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_request_operator_id_remove_request_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='operator_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_booking', to='api.vanoperator'),
        ),
    ]
