# Generated by Django 5.0.6 on 2026-01-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_payment_booking_id_remove_payment_operator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='p_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='p_status',
            new_name='payment_status',
        ),
    ]
