# Generated by Django 5.0.6 on 2026-01-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_payment_time_payment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_time',
            new_name='created_at',
        ),
    ]
