# Generated by Django 5.0.6 on 2026-01-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_request_time_request_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vanoperator',
            old_name='operator_license_doc',
            new_name='operator_license',
        ),
    ]
