# Generated by Django 5.0.6 on 2026-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_operator_license_doc_vanoperator_operator_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingvan',
            name='vanoperator_latitude',
            field=models.DecimalField(decimal_places=6, default=88.8888, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingvan',
            name='vanoperator_longitude',
            field=models.DecimalField(decimal_places=6, default=88.8888, max_digits=9),
            preserve_default=False,
        ),
    ]
