# Generated by Django 5.0.6 on 2026-02-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_chargingvan_vanoperator_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
