# Generated by Django 5.0.6 on 2026-02-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_request_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.vanoperator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uservehicle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_status',
            field=models.IntegerField(default=0),
        ),
    ]
