# Generated by Django 5.0.6 on 2026-02-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_booking', to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_feedbacks', to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='api.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_payments', to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'UPI')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to='api.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_requests', to='api.vanoperator'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Compeletd')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requests', to='api.uservehicle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='is_verified',
            field=models.IntegerField(choices=[(0, 'Not Verified'), (1, 'Verified')], default=0),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vanoperator',
            name='operator_status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=0),
        ),
    ]
