# Generated by Django 5.0.6 on 2026-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Started'), (2, 'Completed')], default=0),
        ),
    ]
