# Generated by Django 5.0.6 on 2026-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvan',
            name='vanoperator_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='chargingvan',
            name='vanoperator_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
