# Generated by Django 5.0.6 on 2026-02-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_chargingvan_vanoperator_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvan',
            name='operator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_van', to='api.vanoperator'),
        ),
    ]
