# Generated by Django 5.0.6 on 2026-02-16 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_chargingvan_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vanoperator'),
        ),
    ]
