# Generated by Django 4.2 on 2026-02-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_chargingvan_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingvan',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vanoperator'),
        ),
    ]
